using System;
using System.IO;
using System.Threading.Tasks;
using FunctionApp.DataAccess;
using FunctionApp.Models;
using FunctionApp.Models.Options;
using FunctionApp.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FunctionApp.Functions
{
    /// <summary>
    /// Stores logs generated by the data factory (or other callers) into the default logging implemented by the
    ///  Azure Function (App Insights)
    /// </summary>
    public class SynapseCancelSparkSessions
    {
        private readonly IOptions<ApplicationOptions> _options;
        private readonly TaskMetaDataDatabase _taskMetaDataDatabase;
        private readonly AzureSynapseService _azureSynapseService;        
        private Guid ExecutionId { get; set; }

        public SynapseCancelSparkSessions(IOptions<ApplicationOptions> options, TaskMetaDataDatabase taskMetaDataDatabase, AzureSynapseService azureSynapseService)
        {
            _options = options;
            _taskMetaDataDatabase = taskMetaDataDatabase;
            _azureSynapseService = azureSynapseService;
        }

        [FunctionName("SynapseCancelSparkSessions")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req,
            ILogger log, ExecutionContext context)
        {
            ExecutionId = context.InvocationId;
            FrameworkRunner frp = new FrameworkRunner(log, ExecutionId);            
            FrameworkRunnerWorkerWithHttpRequest worker = SynapseCancelSparkSessionsCore;
            FrameworkRunnerResult result = await frp.Invoke(req, "SynapseCancelSparkSessions", worker);
            if (result.Succeeded)
            {
                return new OkObjectResult(JObject.Parse(result.ReturnObject));
            }
            else
            {
                return new BadRequestObjectResult(new { Error = "Execution Failed...." });
            }

        }
        public async Task<JObject> SynapseCancelSparkSessionsCore(HttpRequest req,
            Logging.Logging LogHelper)
        {
            try
            {
                string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
                JObject data = JObject.Parse(requestBody);
                //LogHelper.LogInformation("Parsed Main JObject");
                string SparkPoolName = JObject.Parse(data["ExecutionEngine"]["EngineJson"].ToString())["DefaultSparkPoolName"].ToString();
                string Endpoint = JObject.Parse(data["ExecutionEngine"]["EngineJson"].ToString())["endpoint"].ToString();
                LogHelper.LogInformation($"SparkPoolName: {SparkPoolName}; Endpoint: {Endpoint}");
                string JobName = $"TaskInstance_{data["TaskInstanceId"].ToString()}";
                //LogHelper.LogInformation("Calling Stop Idle Sessions");
                await _azureSynapseService.StopIdleSessions(new Uri(Endpoint), SparkPoolName, LogHelper, data);
            }
            catch (Exception ex)
            {
                LogHelper.LogErrors(ex);
            }
            return JObject.Parse("{}");

        }
    }
}