CREATE SCHEMA History;
GO

ALTER TABLE TaskMaster
    ADD
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
            CONSTRAINT DF_TaskMaster_ValidFrom DEFAULT SYSUTCDATETIME()
      , ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
            CONSTRAINT DF_TaskMaster_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999')
      , PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
GO

ALTER TABLE TaskMaster
    SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = History.TaskMaster));
	
ALTER TABLE TaskMasterDependency
   DROP COLUMN ValidFrom;
GO
ALTER TABLE TaskMasterDependency
   DROP COLUMN ValidTo;
GO
ALTER TABLE TaskMasterDependency
    ADD
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
            CONSTRAINT DF_TaskMasterDependency_ValidFrom DEFAULT SYSUTCDATETIME()
      , ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
            CONSTRAINT DF_TaskMasterDependency_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999')
      , PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
GO

ALTER TABLE TaskMasterDependency
    SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = History.TaskMasterDependency));

ALTER TABLE TaskGroup
    ADD
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
            CONSTRAINT DF_TaskGroup_ValidFrom DEFAULT SYSUTCDATETIME()
      , ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
            CONSTRAINT DF_TaskGroup_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999')
      , PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
GO

ALTER TABLE TaskGroup
    SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = History.TaskGroup));

ALTER TABLE SourceAndTargetSystems
    ADD
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
            CONSTRAINT DF_SourceAndTargetSystems_ValidFrom DEFAULT SYSUTCDATETIME()
      , ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
            CONSTRAINT DF_SourceAndTargetSystems_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999')
      , PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
GO

ALTER TABLE SourceAndTargetSystems
    SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = History.SourceAndTargetSystems));
	
ALTER TABLE TaskInstance
    ADD
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
            CONSTRAINT DF_TaskInstance_ValidFrom DEFAULT SYSUTCDATETIME()
      , ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
            CONSTRAINT DF_TaskInstance_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999')
      , PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
GO

ALTER TABLE TaskInstance
    SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = History.TaskInstance));
	