// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Method - Is Invoked by function runtime", Scope = "member", Target = "~M:FunctionApp.Functions.AdfGetActivityRunsTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Method - Is Invoked by function runtime", Scope = "member", Target = "~M:FunctionApp.Functions.AdfRunFrameworkTasksTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "ASP.Net Core Options Class - Needs to be read/write", Scope = "member", Target = "~P:FunctionApp.Models.Options.ServiceConnections.CoreFunctionsAllowedRoles")]
[assembly: SuppressMessage("Design", "CA1028:Enum Storage should be Int32", Justification = "Underlying datatype in SQL table is a short. Makes for consistent types", Scope = "type", Target = "~T:FunctionApp.Logging.Logging.LogType")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "JsonSerialisation", Scope = "member", Target = "~P:FunctionApp.Helpers.JsonObjectPropertyList.Properties")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.AdfGetActivityRunsTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.AdfGetPipelineRunsTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.AppInsightsGetActivityLevelLogsTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.ProcessChangeFeedTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.AdfGetActivityErrorsTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.AdfPrepareFrameworkTasksTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.AdfGetPipelineRunsTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.AdfPrepareFrameworkTasksTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.ProcessChangeFeedTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.AdfGetActivityErrorsTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.AdfRunFrameworkTasksHttpTrigger.Run(Microsoft.AspNetCore.Http.HttpRequest,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext,System.Security.Claims.ClaimsPrincipal)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Azure Function Timer", Scope = "member", Target = "~M:FunctionApp.Functions.AdfRunFrameworkTasksTimerTrigger.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)")]
[assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:FunctionApp.Functions.AzStorageCacheFileListGenerateSas.Run(Microsoft.AspNetCore.Http.HttpRequest,Microsoft.Extensions.Logging.ILogger,Microsoft.Azure.WebJobs.ExecutionContext)~Microsoft.AspNetCore.Mvc.IActionResult")]
